### ISSUE TITLE
Navigation needs work

### ISSUE THREAD

**Issue by anchit-chandran** [rcpch/rcpch-api-management-platform#8]
The various navigation steps to get to your desired content seem confusing even to me. I think it just needs better wiring up of links + wording.

E.g. clicking on `APIs` in the top navbar takes you https://dev.rcpch.ac.uk/tiers - showing available API Tier plans , but I think it's more logical for it to take you to a page that sees available APIs at https://dev.rcpch.ac.uk/apis

If you're happy for me to have a crack at better userflow @pacharanero , will do this. Azure does have 'revisions' every time you publish, so can always roll back.

Hopefully better userflow means easier to explain in docs related to #5

**Comment by pacharanero** [comment]
Closing as the nav on the Azure APIM is probably about as good as we're going to get it given the inherent handicap of the drag'n'drop templating system that Azure APIM uses.
